services:
  dashboard:
    build:
      context: ./dashboard
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:8080"
    env_file:
      - ./dashboard/.env
    volumes:
      - ./dashboard:/app
      - /app/node_modules # This is often done to ensure that the node_modules directory inside the container is isolated and not affected by the host machine's environment. It can also prevent the host's node_modules from being overwritten by the container's and also prevent issues with modules that are platform-specific.
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3001:8080"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules # This is often done to ensure that the node_modules directory inside the container is isolated and not affected by the host machine's environment. It can also prevent the host's node_modules from being overwritten by the container's and also prevent issues with modules that are platform-specific.
    depends_on:
      - database
    networks:
      - app-network
  database:
    image: mongo:8.0.10 # Use the official MongoDB image from Docker Hub
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db # Persist data within the host machine
    networks:
      - app-network
    command: mongod --replSet rs0 --bind_ip_all

networks:
  app-network:
    driver: bridge
